[2023-12-03 18:23:58,386] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.running_automation manual__2023-12-03T18:19:58.440199+00:00 [queued]>
[2023-12-03 18:23:58,405] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dag_automation_daily.running_automation manual__2023-12-03T18:19:58.440199+00:00 [queued]>
[2023-12-03 18:23:58,405] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 18:23:58,405] {taskinstance.py:1357} INFO - Starting attempt 2 of 3
[2023-12-03 18:23:58,406] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-12-03 18:23:58,435] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): running_automation> on 2023-12-03 18:19:58.440199+00:00
[2023-12-03 18:23:58,443] {standard_task_runner.py:52} INFO - Started process 638 to run task
[2023-12-03 18:23:58,449] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_automation_daily', 'running_automation', 'manual__2023-12-03T18:19:58.440199+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpi7i4kkfv', '--error-file', '/tmp/tmptcjysvxe']
[2023-12-03 18:23:58,450] {standard_task_runner.py:80} INFO - Job 44: Subtask running_automation
[2023-12-03 18:23:58,569] {task_command.py:369} INFO - Running <TaskInstance: dag_automation_daily.running_automation manual__2023-12-03T18:19:58.440199+00:00 [running]> on host c9140d11a0a8
[2023-12-03 18:23:58,878] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=sebastiancahyoardhiiswara@gmail.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_automation_daily
AIRFLOW_CTX_TASK_ID=running_automation
AIRFLOW_CTX_EXECUTION_DATE=2023-12-03T18:19:58.440199+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-12-03T18:19:58.440199+00:00
[2023-12-03 18:23:58,883] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-12-03 18:23:58,885] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python codes/automation.py']
[2023-12-03 18:23:59,000] {subprocess.py:85} INFO - Output:
[2023-12-03 18:24:04,700] {subprocess.py:92} INFO - (psycopg2.errors.DependentObjectsStillExist) cannot drop table dim_province because other objects depend on it
[2023-12-03 18:24:04,701] {subprocess.py:92} INFO - DETAIL:  constraint dim_district_province_id_fkey on table dim_district depends on table dim_province
[2023-12-03 18:24:04,702] {subprocess.py:92} INFO - constraint fact_province_daily_province_id_fkey on table fact_province_daily depends on table dim_province
[2023-12-03 18:24:04,702] {subprocess.py:92} INFO - HINT:  Use DROP ... CASCADE to drop the dependent objects too.
[2023-12-03 18:24:04,702] {subprocess.py:92} INFO - 
[2023-12-03 18:24:04,703] {subprocess.py:92} INFO - [SQL:
[2023-12-03 18:24:04,703] {subprocess.py:92} INFO - DROP TABLE dim_province]
[2023-12-03 18:24:04,704] {subprocess.py:92} INFO - (Background on this error at: http://sqlalche.me/e/14/2j85)
[2023-12-03 18:24:04,704] {subprocess.py:92} INFO - (psycopg2.errors.DependentObjectsStillExist) cannot drop table dim_district because other objects depend on it
[2023-12-03 18:24:04,705] {subprocess.py:92} INFO - DETAIL:  constraint fact_district_daily_district_id_fkey on table fact_district_daily depends on table dim_district
[2023-12-03 18:24:04,705] {subprocess.py:92} INFO - HINT:  Use DROP ... CASCADE to drop the dependent objects too.
[2023-12-03 18:24:04,705] {subprocess.py:92} INFO - 
[2023-12-03 18:24:04,706] {subprocess.py:92} INFO - [SQL:
[2023-12-03 18:24:04,706] {subprocess.py:92} INFO - DROP TABLE dim_district]
[2023-12-03 18:24:04,707] {subprocess.py:92} INFO - (Background on this error at: http://sqlalche.me/e/14/2j85)
[2023-12-03 18:24:04,707] {subprocess.py:92} INFO - (psycopg2.errors.DependentObjectsStillExist) cannot drop table dim_case because other objects depend on it
[2023-12-03 18:24:04,708] {subprocess.py:92} INFO - DETAIL:  constraint fact_province_daily_case_id_fkey on table fact_province_daily depends on table dim_case
[2023-12-03 18:24:04,712] {subprocess.py:92} INFO - constraint fact_district_daily_case_id_fkey on table fact_district_daily depends on table dim_case
[2023-12-03 18:24:04,713] {subprocess.py:92} INFO - HINT:  Use DROP ... CASCADE to drop the dependent objects too.
[2023-12-03 18:24:04,713] {subprocess.py:92} INFO - 
[2023-12-03 18:24:04,714] {subprocess.py:92} INFO - [SQL:
[2023-12-03 18:24:04,718] {subprocess.py:92} INFO - DROP TABLE dim_case]
[2023-12-03 18:24:04,723] {subprocess.py:92} INFO - (Background on this error at: http://sqlalche.me/e/14/2j85)
[2023-12-03 18:24:05,486] {subprocess.py:96} INFO - Command exited with return code 0
[2023-12-03 18:24:05,596] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=dag_automation_daily, task_id=running_automation, execution_date=20231203T181958, start_date=20231203T182358, end_date=20231203T182405
[2023-12-03 18:24:05,679] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-12-03 18:24:05,794] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
